"""Centralized tunable thresholds for calculator and analyzer logic."""

# Time sanity
MIN_RELIABLE_ROUNDS_PER_HOUR = 5.0

# Sample-size guards
SMALL_SAMPLE_ROUNDS = 120
LOW_CONFIDENCE_OVERALL = 0.45

# Clutch insights
CLUTCH_LOW_SUCCESS_ATTEMPT_RATE = 0.12
CLUTCH_LOW_SUCCESS_THRESHOLD = 0.22
CLUTCH_STRONG_SUCCESS_THRESHOLD = 0.30
CLUTCH_MIN_STRONG_SAMPLE = 20

CLUTCH_BURDEN_ATTEMPT_RATE = 0.14
CLUTCH_BURDEN_DISADV_SHARE = 0.70
CLUTCH_BURDEN_MIN_ATTEMPTS = 40

EXTREME_CLUTCH_MIN_ATTEMPTS = 20
EXTREME_CLUTCH_MIN_TOTAL_ATTEMPTS = 40

HIGH_PRESSURE_MIN_ATTEMPT_RATE = 0.03
HIGH_PRESSURE_MIN_ATTEMPTS = 10
HIGH_PRESSURE_LOW_SUCCESS = 0.12
HIGH_PRESSURE_STRONG_SUCCESS = 0.20

# Efficiency volume
EFFICIENCY_MIN_HOURS = 50.0
EFFICIENCY_LOW_WINS_PER_HOUR = 0.12

# Teamkill / discipline
TEAMKILL_RATE_MEDIUM = 0.02
TEAMKILL_RATE_LOW = 0.01
CLEAN_PLAY_NORMALIZATION_RATE = TEAMKILL_RATE_MEDIUM

# Severity bands for teamkill-derived discipline messaging.
TEAMKILL_SEVERITY_BANDS = (
    (TEAMKILL_RATE_MEDIUM, "medium"),
    (TEAMKILL_RATE_LOW, "low"),
)

